### ISSUE TITLE
hengshuai's blog | hengshuai's blog

### ISSUE THREAD

**Issue by ihengshuai** [ihengshuai/blog#42]
https://blog.usword.cn/super-nav/index.html 

 a blog for sharing web development experiences...

**Comment by ihengshuai** [comment]
这里用yaml语法展示友链
```yml
avatar: https://tva1.sinaimg.cn/large/005HV6Avgy1h76xsijlrij30u00u0diz.jpg
name: ihengshuai
title: A passionate web developer base on ShenZhen
links:
  - icon: github
    link: http://github.com/ihengshuai
  - icon: blog
    link: http://blog.usword.cn
  - icon: juejin
    link: https://juejin.cn/user/2999123453679656
```
